version: "3"
services:
        backend:
                container_name: node-restserver
                restart: always
                build: .
                ports:
                        - "8000:8000"
        mongodb:
                container_name: mongodb
                image: mongo
                volumes:
                        - ./restserver-data:/data/db
                ports:
                        - '27017:27017'
